// Login Register
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILED = "REGISTER_FAILED";
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILED = "LOGIN_FAILED";
export const LOGOUT_REQUEST = "LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const LOGOUT_FAILED = "LOGOUT_FAILED";
export const GET_USER_REQUEST = "GET_USER_REQUEST";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const GET_USER_FAILED = "GET_USER_FAILED";

//Campaign
export const LIST_CAMPAIGN_REQUEST = "LIST_CAMPAIGN_REQUEST";
export const LIST_CAMPAIGN_SUCCESS = "LIST_CAMPAIGN_SUCCESS";
export const LIST_CAMPAIGN_FAILED = "LIST_CAMPAIGN_FAILED";
export const DETAIL_CAMPAIGN_REQUEST = "DETAIL_CAMPAIGN_REQUEST";
export const DETAIL_CAMPAIGN_SUCCESS = "DETAIL_CAMPAIGN_SUCCESS";
export const DETAIL_CAMPAIGN_FAILED = "DETAIL_CAMPAIGN_FAILED";